---
- hosts: all
  connection: local
  gather_facts: yes
  # become: yes
  become_method: sudo
  vars_files:
    - vault/aws.yml
    - vault/repos.yml
    - vault/ssl.yml
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    local_home: "{{ lookup('env', 'HOME') }}"
    bin_path: "{{ local_home }}/.local/bin"
    data_dir: "{{ local_home }}/.local/share"
    os_family: "{{ ansible_os_family | lower }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"
    architecture: "{{ ansible_architecture }}"
  environment:
  roles:
    - role: base
    - role: debian
      when: ansible_facts['os_family'] == 'Debian' and ('WSL_DISTRO_NAME' not in ansible_env and 'C9_PROJECT' not in ansible_env)
    - role: remote
      when: ansible_facts['os_family'] == 'Debian' and ('WSL_DISTRO_NAME' in ansible_env or 'C9_PROJECT' in ansible_env)
    - role: macos
      when: ansible_facts['os_family'] == 'Darwin'
