user_groups:
  - sudo

bashrc_includes:
  - "[ -f ~/.bash_profile ] && . ~/.bash_profile"

packages:
  - apt-file
  - apt-transport-https
  - aria2
  - bash-completion
  - build-essential
  - byobu
  - ca-certificates
  - curl
  - direnv
  - exfat-fuse
  - exfat-utils
  - git
  - helm
  - htop
  - httpie
  - jq
  - kubectl
  - make
  - nmap
  - openssh-server
  - p7zip-full
  - podman
  - python3-pip
  - ruby
  - software-properties-common
  - telnet
  - traceroute
  - vim
  - wget
  - xz-utils
  - zip

remote_packages: []

remote_executables:
  - name: vagrant
    url: "https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_linux_amd64.zip"
  - name: packer
    url: "https://releases.hashicorp.com/packer/1.6.5/packer_1.6.5_linux_amd64.zip"
  - name: terraform
    url: "https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip"
  - name: terragrunt
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v0.26.7/terragrunt_linux_amd64"

vscode:
  extensions:
    - 4ops.terraform
    - AmazonWebServices.aws-toolkit-vscode
    - CoenraadS.bracket-pair-colorizer-2
    - d4nyll.devops-extension-pack
    - donjayamanne.git-extension-pack
    - donjayamanne.python-extension-pack
    - EditorConfig.EditorConfig
    - formulahendry.docker-explorer
    - Gruntfuggly.todo-tree
    - HashiCorp.terraform
    - marclipovsky.string-manipulation
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.vscode-remote-extensionpack
    - PKief.material-icon-theme
    - quicktype.quicktype
    - scala-lang.scala
    - Tyriar.sort-lines
    - vscjava.vscode-java-pack
    - vscode-icons-team.vscode-icons
  settings: {
    "[ansible]": {
      "editor.detectIndentation": false,
      "editor.insertSpaces": true,
      "editor.tabSize": 2
    },
    "editor.renderWhitespace": true,
    "editor.rulers": [
      80,
      100,
      120
    ],
    "files.associations": {
      "**/ansible/**/hosts": "ini",
      "**/ansible/**/inventory": "ini",
      "**/defaults/**/*.yml": "jinja-yaml",
      "**/group_vars/**/*": "jinja-yaml",
      "**/handlers/*.yml": "ansible",
      "**/host_vars/**/*": "jinja-yaml",
      "**/meta/*.yml": "ansible",
      "**/playbooks/**/*.yml": "ansible",
      "**/roles/**/*.yml": "ansible",
      "**/tasks/**/*.yml": "ansible",
      "**/vars/**/*.yml": "jinja-yaml",
      "Vagrantfile": "ruby",
      "ansible.cfg": "ini"
    },
    "files.autoSave": "afterDelay",
    "projectManager.any.baseFolders": [
      "~/projects"
    ],
    "projectManager.any.maxDepthRecursion": 2,
    "workbench.iconTheme": "vscode-icons"
  }
