---

- name: Inserting bash 4 to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "/opt/homebrew/bin/bash"
  become: true

# - name: Change default shell to bash 4
#   shell: chsh -s /opt/homebrew/bin/bash

- name: Inserting itens in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items: "{{ bashrc_includes }}"

# - name: nvm
#   shell: >
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
#   args:
#     creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Update homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew }}"
  ignore_errors: yes

- name: Install brew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask }}"
  ignore_errors: yes

- name: Install VSCode Extensions
  command: "code --install-extension {{ item }} --force"
  loop: "{{ vscode.extensions }}"
  ignore_errors: yes

#- name: Write VSCode Settings
#  template:
#    src: settings.json.j2
#    dest: "~/workspace.code-workspace"
#    force: yes
#    mode: 0644
