repositories:
  ppa: []
  url:
    - "deb https://download.docker.com/linux/ubuntu groovy stable"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://baltocdn.com/helm/stable/debian/ all main"
  key:
    - url: "https://download.docker.com/linux/ubuntu/gpg"
    - url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    - url: "https://baltocdn.com/helm/signing.asc"

remote_executables:
   - name: packer
     url: "https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_arm64.zip"
   - name: terraform
     url: "https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_arm64.zip"
   - name: terragrunt
     url: "https://github.com/gruntwork-io/terragrunt/releases/download/v0.27.1/terragrunt_linux_amd64"
