repositories:
  ppa: []
  url:
    # - "deb http://dl.google.com/linux/chrome/deb/ stable main"
    # - "deb https://download.virtualbox.org/virtualbox/debian focal contrib"
    # - "deb https://mega.nz/linux/MEGAsync/xUbuntu_20.04/ ./"
    # - "deb https://download.docker.com/linux/ubuntu focal stable"
    # - "deb https://packages.microsoft.com/repos/vscode stable main"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://baltocdn.com/helm/stable/debian/ all main"
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
  key:
    # - url: "https://dl.google.com/linux/linux_signing_key.pub"
    # - url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    # - url: "https://www.virtualbox.org/download/oracle_vbox.asc"
    # - url: "https://mega.nz/linux/MEGAsync/xUbuntu_20.04/Release.key"
    # - url: "https://download.docker.com/linux/ubuntu/gpg"
    # - url: "https://packages.microsoft.com/keys/microsoft.asc"
    - url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    - url: "https://baltocdn.com/helm/signing.asc"
    - url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key"



sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update -qq
sudo apt-get -qq -y install podman
sudo mkdir -p /etc/containers
echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf
